// <auto-generated />
using System;
using CoordinateRegistration.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoordinateRegistration.Persistence.Migrations
{
    [DbContext(typeof(CoordinateRegistrationDbContext))]
    [Migration("20250211000005_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoordinateRegistration.Domain.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("SmallDatetime");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("SmallDatetime");

                    b.Property<Guid>("Hash")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MarkerId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("MarkerId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.Marker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("SmallDatetime");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("SmallDatetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("Hash")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Marker");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.MarkerTypeOccurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Hash")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MarkerId")
                        .HasColumnType("int");

                    b.Property<int>("TypeOccurrenceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarkerId");

                    b.HasIndex("TypeOccurrenceId");

                    b.ToTable("MarkerTypeOccurrence");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.ProfileUsr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Hash")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("ProfileUsr");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hash = new Guid("d44a56d9-fe82-4213-9e74-6de492dd3d5e"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Hash = new Guid("f6052b15-acf4-44ad-996c-fdf90c019404"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("SmallDatetime");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("SmallDatetime");

                    b.Property<Guid>("Hash")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MarkerId")
                        .HasColumnType("int");

                    b.Property<bool>("Negative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Positive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("MarkerId");

                    b.HasIndex("UserId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.TypeOccurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("SmallDatetime");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("SmallDatetime");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("SmallDatetime");

                    b.Property<Guid>("Hash")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserDeleteId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserUpdateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("UserDeleteId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserUpdateId");

                    b.ToTable("TypeOccurrence");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("SmallDatetime");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("SmallDatetime");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("SmallDatetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("Hash")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("PasswordDateRequest")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RecoveryHash")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("RecoveryHash")
                        .IsUnique()
                        .HasFilter("[RecoveryHash] IS NOT NULL");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = false,
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@admin.com.br",
                            Hash = new Guid("e8bec31a-ed0c-4762-9011-f4b3d69eb6cc"),
                            Name = "Admin",
                            Password = "0f2797f2182804d0cc7f0b85d254c146"
                        });
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Hash")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProfile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hash = new Guid("583383e7-4b31-4b1b-9d54-5c5b155b11e3"),
                            ProfileId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.Comment", b =>
                {
                    b.HasOne("CoordinateRegistration.Domain.Marker", "Marker")
                        .WithMany("Comment")
                        .HasForeignKey("MarkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoordinateRegistration.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Marker");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.Marker", b =>
                {
                    b.HasOne("CoordinateRegistration.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.MarkerTypeOccurrence", b =>
                {
                    b.HasOne("CoordinateRegistration.Domain.Marker", "Marker")
                        .WithMany("MarkerTypeOccurrences")
                        .HasForeignKey("MarkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoordinateRegistration.Domain.TypeOccurrence", "TypeOccurrence")
                        .WithMany("MarkerTypeOccurrences")
                        .HasForeignKey("TypeOccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marker");

                    b.Navigation("TypeOccurrence");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.Review", b =>
                {
                    b.HasOne("CoordinateRegistration.Domain.Marker", "Marker")
                        .WithMany("Reviews")
                        .HasForeignKey("MarkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoordinateRegistration.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Marker");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.TypeOccurrence", b =>
                {
                    b.HasOne("CoordinateRegistration.Domain.User", "UserDelete")
                        .WithMany()
                        .HasForeignKey("UserDeleteId");

                    b.HasOne("CoordinateRegistration.Domain.User", "UserCreate")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("CoordinateRegistration.Domain.User", "UserUpdate")
                        .WithMany()
                        .HasForeignKey("UserUpdateId");

                    b.Navigation("UserCreate");

                    b.Navigation("UserDelete");

                    b.Navigation("UserUpdate");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.UserProfile", b =>
                {
                    b.HasOne("CoordinateRegistration.Domain.ProfileUsr", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoordinateRegistration.Domain.User", null)
                        .WithMany("Profile")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.Marker", b =>
                {
                    b.Navigation("Comment");

                    b.Navigation("MarkerTypeOccurrences");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.TypeOccurrence", b =>
                {
                    b.Navigation("MarkerTypeOccurrences");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.User", b =>
                {
                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
