// <auto-generated />
using System;
using CoordinateRegistration.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoordinateRegistration.Persistence.Migrations
{
    [DbContext(typeof(CoordinateRegistrationDbContext))]
    [Migration("20260226030529_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoordinateRegistration.Domain.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("SmallDatetime");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("SmallDatetime");

                    b.Property<Guid>("Hash")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MarkerId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("MarkerId");

                    b.HasIndex("PersonId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.Marker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("SmallDatetime");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("SmallDatetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("Hash")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("PersonId");

                    b.ToTable("Marker");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.MarkerTypeOccurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Hash")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MarkerId")
                        .HasColumnType("int");

                    b.Property<int>("TypeOccurrenceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarkerId");

                    b.HasIndex("TypeOccurrenceId");

                    b.ToTable("MarkerTypeOccurrence");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("SmallDatetime");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("SmallDatetime");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("SmallDatetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("Hash")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("PasswordDateRequest")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RecoveryHash")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("RecoveryHash")
                        .IsUnique()
                        .HasFilter("[RecoveryHash] IS NOT NULL");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = false,
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@admin.com.br",
                            Hash = new Guid("9772edc4-764c-4576-b864-bdd889369bc2"),
                            Name = "Admin",
                            Password = "4de93544234adffbb681ed60ffcfb941"
                        });
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.PersonProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Hash")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProfileId");

                    b.ToTable("PersonProfile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hash = new Guid("e3814f9b-e3df-442e-be80-3c79ce26a0c2"),
                            PersonId = 1,
                            ProfileId = 1
                        });
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.ProfileUsr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Hash")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("ProfileUsr");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hash = new Guid("8abf25ba-cf18-4770-be7a-006c739fcba7"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Hash = new Guid("4d726080-a763-47c0-b15a-7fca707e00e3"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("SmallDatetime");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("SmallDatetime");

                    b.Property<Guid>("Hash")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MarkerId")
                        .HasColumnType("int");

                    b.Property<bool>("Negative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<bool>("Positive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("MarkerId");

                    b.HasIndex("PersonId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.TypeOccurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("SmallDatetime");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("SmallDatetime");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("SmallDatetime");

                    b.Property<Guid>("Hash")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PersonDeleteId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonUpdateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("PersonDeleteId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PersonUpdateId");

                    b.ToTable("TypeOccurrence");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.Comment", b =>
                {
                    b.HasOne("CoordinateRegistration.Domain.Marker", "Marker")
                        .WithMany("Comment")
                        .HasForeignKey("MarkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoordinateRegistration.Domain.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.Navigation("Marker");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.Marker", b =>
                {
                    b.HasOne("CoordinateRegistration.Domain.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.MarkerTypeOccurrence", b =>
                {
                    b.HasOne("CoordinateRegistration.Domain.Marker", "Marker")
                        .WithMany("MarkerTypeOccurrences")
                        .HasForeignKey("MarkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoordinateRegistration.Domain.TypeOccurrence", "TypeOccurrence")
                        .WithMany("MarkerTypeOccurrences")
                        .HasForeignKey("TypeOccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marker");

                    b.Navigation("TypeOccurrence");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.PersonProfile", b =>
                {
                    b.HasOne("CoordinateRegistration.Domain.Person", null)
                        .WithMany("Profile")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoordinateRegistration.Domain.ProfileUsr", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.Review", b =>
                {
                    b.HasOne("CoordinateRegistration.Domain.Marker", "Marker")
                        .WithMany("Reviews")
                        .HasForeignKey("MarkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoordinateRegistration.Domain.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.Navigation("Marker");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.TypeOccurrence", b =>
                {
                    b.HasOne("CoordinateRegistration.Domain.Person", "PersonDelete")
                        .WithMany()
                        .HasForeignKey("PersonDeleteId");

                    b.HasOne("CoordinateRegistration.Domain.Person", "PersonCreate")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("CoordinateRegistration.Domain.Person", "PersonUpdate")
                        .WithMany()
                        .HasForeignKey("PersonUpdateId");

                    b.Navigation("PersonCreate");

                    b.Navigation("PersonDelete");

                    b.Navigation("PersonUpdate");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.Marker", b =>
                {
                    b.Navigation("Comment");

                    b.Navigation("MarkerTypeOccurrences");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.Person", b =>
                {
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CoordinateRegistration.Domain.TypeOccurrence", b =>
                {
                    b.Navigation("MarkerTypeOccurrences");
                });
#pragma warning restore 612, 618
        }
    }
}
